# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.07
      - image: circleci/postgres:13.4
        environment:
          POSTGRES_USER: circle
          POSTGRES_DB: test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Download Flyway
          command: wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.14.0/flyway-commandline-7.14.0-linux-x64.tar.gz | tar xvz && sudo ln -s `pwd`/flyway-7.14.0/flyway /usr/local/bin
      - run:
          name: Migrate
          command: flyway -community -url=jdbc:postgresql://localhost:5432/test -user=circle migrate
      - run:
          name: Output db info
          command: flyway -community -url=jdbc:postgresql://localhost:5432/test -user=circle info



workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build