# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: flyway/flyway:latest
      - image: circleci/postgres:13.4
        environment:
          POSTGRES_USER: circle
          POSTGRES_DB: test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: docker run --rm flyway/flyway -url=jdbc:postgresql://localhost/test -user=circle info

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build